name: Setup
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: 'yarn'
    - run: yarn --immutable
      shell: bash
