name: Deploy
inputs:
  sha:
    description: "Git commit sha"
    required: true
  prNum:
    description: "pull request number for preview"
    default: ""
runs:
  using: composite
  steps:
  - uses: 'google-github-actions/deploy-cloudrun@v0'
    with:
      service: 'portfolio-webapp'
      image: 'gcr.io/izumin-portfolio/portfolio-webapp:${{ inputs.sha }}'
      env_vars: NODE_ENV=production,PREVIEWED_PR_NUM:${{ inputs.prNum }}
      secrets: |
        ASSET_URL_BASE=portfolio-webapp-ASSET_URL_BASE:latest
        SENTRY_DSN=portfolio-webapp-SENTRY_DSN:latest
      tag: ${{ inputs.prNum != "" AND format('pr{1}', inputs.prNum) }}
      no_traffic: ${{ inputs.prNum != '' }}
