name: Deploy
inputs:
  name:
    description: "App name"
  sha:
    description: "Git commit sha"
    required: true
  prNum:
    description: "pull request number for preview"
    default: ""
runs:
  using: composite
  steps:
  - name: Deploy new revision
    uses: 'google-github-actions/deploy-cloudrun@v0'
    with:
      service: ${{ inputs.name }}
      image: 'gcr.io/izumin-portfolio/${{ inputs.name }}:${{ inputs.sha }}'
      env_vars: |
        NODE_ENV=production
        PREVIEWED_PR_NUM=${{ inputs.prNum != '' && inputs.prNum || '""' }}
      tag: ${{ inputs.prNum != '' && format('pr{0}', inputs.prNum) || '' }}
      no_traffic: ${{ inputs.prNum != '' }}
  - name: Update traffic to LATEST revision
    uses: 'google-github-actions/deploy-cloudrun@v0'
    with:
      service: ${{ inputs.name }}
      revision_traffic: LATEST=100
    if: ${{ inputs.prNum == '' }}
