name: Deploy
inputs:
  sha:
    description: "Git commit sha"
    required: true
  prNum:
    description: "pull request number for preview"
    default: ""
runs:
  using: composite
  steps:
  - name: Deploy new revision
    uses: 'google-github-actions/deploy-cloudrun@v0'
    with:
      service: 'portfolio-webapp'
      image: 'gcr.io/izumin-portfolio/portfolio-webapp:${{ inputs.sha }}'
      env_vars: |
        NODE_ENV=production
        ${{ inputs.prNum != '' && format('PREVIEWED_PR_NUM=${0}', inputs.prNum) || '' }}
      secrets: |
        ASSET_URL_BASE=portfolio-webapp-ASSET_URL_BASE:latest
        SENTRY_DSN=portfolio-webapp-SENTRY_DSN:latest
      tag: ${{ inputs.prNum != '' && format('pr{0}', inputs.prNum) || '' }}
      no_traffic: ${{ inputs.prNum != '' }}
      flags: |
        --clear-env-vars
        --clear-secrets
  - name: Update traffic to LATEST revision
    uses: 'google-github-actions/deploy-cloudrun@v0'
    with:
      service: 'portfolio-webapp'
      revision_traffic: LATEST=100
    if: ${{ inputs.prNum == '' }}
