name: Deploy
inputs:
  sha:
    description: "Git commit sha"
    required: true
  previewTag:
    description: "Tag for pull request preview"
    default: ""
runs:
  using: composite
  steps:
  - uses: 'google-github-actions/deploy-cloudrun@v0'
    with:
      service: 'portfolio-webapp'
      image: 'gcr.io/izumin-portfolio/portfolio-webapp:${{ inputs.sha }}'
      env_vars: NODE_ENV=production
      secrets: |
        ASSET_URL_BASE=portfolio-webapp-ASSET_URL_BASE:latest
        SENTRY_DSN=portfolio-webapp-SENTRY_DSN:latest
      tag: ${{ inputs.previewTag }}
      no_traffic: ${{ inputs.previewTag != '' }}
