name: Docker build and push
inputs:
  dockerfile:
    description: "Dockerfile path"
    required: true
  name:
    description: "App name used for image tag"
    required: true
runs:
  using: composite
  steps:
  - uses: docker/setup-buildx-action@v1
  - uses: google-github-actions/setup-gcloud@v0
  - shell: bash
    run: |
      gcloud auth configure-docker
  - uses: actions/cache@v3
    with:
      path: /tmp/.buildx-cache
      key: ${{ runner.os }}-buildx-${{ github.sha }}
      restore-keys: |
        ${{ runner.os }}-buildx-
  - shell: bash
    id: vars
    run: echo "::set-output name=git-sha::${GITHUB_SHA::7}"
  - uses: docker/build-push-action@v2
    with:
      context: .
      push: true
      tags: gcr.io/izumin-portfolio/${{ inputs.name }}:${{ steps.vars.outputs.git-sha }}
      cache-from: type=local,src=/tmp/.buildx-cache
      cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      file: ${{ inputs.dockerfile }}
      secret-files: |
        dotenv=.env
  # Temp fix
  # https://github.com/docker/build-push-action/issues/252
  # https://github.com/moby/buildkit/issues/1896
  - shell: bash
    name: Move cache
    run: |
      rm -rf /tmp/.buildx-cache
      mv /tmp/.buildx-cache-new /tmp/.buildx-cache
