// Code generated by scripts/gen-next-routes.mjs. DO NOT EDIT.

/* eslint-disable */

import type * as typesindex from "./pages/index";
export type Routes = {
  "/blog/[...path]": {
    query: {};
  };
  "/": {
    query: typesindex.Query;
  };
};
declare global {
  interface NextRoutes extends Routes {}
}
