name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.node-version'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn lint

  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.node-version'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.node-version'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn test --ci --coverage

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.node-version'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn build
