name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "**"

jobs:
  ensure-git-status-clean:
    runs-on: ubuntu-latest
    name: Clean
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup
    - run: yarn clean
    - run: yarn generate
    - name: Check there is no diff
      run: |
        if test -n "$(git status --porcelain)"; then
          git status
          git diff
          exit 1
        fi

  lint:
    runs-on: ubuntu-latest
    name: Lint
    if: "github.event_name == 'pull_request'"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/actions/setup
    - run: yarn lint

  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup
    - run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup
    # TODO: run test on all packages
    - run: yarn test --filter @izumin5210/portfolio-webapp -- --ci --coverage

  build:
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        include:
          - name: portfolio-webapp
            path: ./apps/web
            preview-url-comment: true
          - name: portfolio-graphql-gateway
            path: ./apps/graphql-gateway
    name: Build ${{ matrix.name }}
    with:
      name: ${{ matrix.name }}
      path: ${{ matrix.path }}
    secrets:
      GOOGLE_COULD_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GOOGLE_COULD_WORKLOAD_IDENTITY_PROVIDER }}
      GOOGLE_CLOUD_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: [ensure-git-status-clean, typecheck, test, build]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: 'read'
      id-token: 'write'
    environment:
      name: production
      url: https://izum.in
    concurrency:
      group: production
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - id: vars
      run: echo "::set-output name=git-sha::${GITHUB_SHA::7}"
    - uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.GOOGLE_COULD_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}
        access_token_lifetime: 600s
    - uses: ./.github/actions/deploy
      with:
        name: portfolio-graphql-gateway
        sha: ${{ steps.vars.outputs.git-sha }}
    - uses: ./.github/actions/deploy
      with:
        name: portfolio-webapp
        sha: ${{ steps.vars.outputs.git-sha }}
