name: Cleanup PR

on:
  pull_request:
    types:
    - closed

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      pull-requests: 'write'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2
    - uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.GOOGLE_COULD_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}
        access_token_lifetime: 600s
    - uses: 'google-github-actions/setup-gcloud@v0'
    - name: Install beta component
      run: gcloud components install --quiet beta
    - name: Delete preview
      run: |
        gcloud beta run services update-traffic portfolio-webapp \
          --region us-central1 \
          --remove-tags pr${{ github.event.pull_request.number }}
    - uses: ./.github/actions/preview-comment
      with:
        prNumber: ${{ github.event.pull_request.number }}
        sha: ${{ github.event.pull_request.head.sha }}
        delete: true
